site_name: pybox

theme:
  name: material

markdown_extensions:
  - smarty

watch:
  - ./pybox

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          do_something: true
          heading_level: 2
          show_root_toc_entry: false
          show_root_full_path: false
          show_category_heading: true
          members_order: "source"
          docstring_section_style: "list"
          show_signature_annotations: true

nav:
  - Index: index.md
  - Reference:  
    - Button Module: button.md
    - Led Module: led.md
    - Ring Module: ring.md
  - Exercises:
    - Button: tut_button.md
    - Led: tut_led.md
    - Ring: tut_ring.md
