site_name: pybox

theme:
  name: windmill

plugins:
  - mkdocstrings

markdown_extensions:
  - smarty

watch:
  - ./pybox

nav:
  - Index: index.md
  - Reference:  
    - Button: button.md
    - Led: led.md
  - Exercises:
    - Button: tut_button.md
    - Led: tut_led.md
